extends MeshInstance3D

func _ready() -> void:
	var grid_array := []
	grid_array.resize(Mesh.ARRAY_MAX)
	grid_array[Mesh.ARRAY_VERTEX] = PackedVector3Array()
	grid_array[Mesh.ARRAY_COLOR] = PackedColorArray()
	# horizontal cross middle
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(1.0,0,0))
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(-1.0,0,0))
	grid_array[Mesh.ARRAY_COLOR].append(Color.BLUE)
	grid_array[Mesh.ARRAY_COLOR].append(Color.BLUE)
	#vertical cross middle
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(0,0,1))
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(0,0,-1))
	grid_array[Mesh.ARRAY_COLOR].append(Color.BLUE)
	grid_array[Mesh.ARRAY_COLOR].append(Color.BLUE)
	#vetical grid +4 , 0.2 increment
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(1,0,1))
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(1,0,-1))
	grid_array[Mesh.ARRAY_COLOR].append(Color.WEB_GREEN)
	grid_array[Mesh.ARRAY_COLOR].append(Color.WEB_GREEN)
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(0.8,0,1))
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(0.8,0,-1))
	grid_array[Mesh.ARRAY_COLOR].append(Color.WEB_GREEN)
	grid_array[Mesh.ARRAY_COLOR].append(Color.WEB_GREEN)
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(0.6,0,1))
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(0.6,0,-1))
	grid_array[Mesh.ARRAY_COLOR].append(Color.WEB_GREEN)
	grid_array[Mesh.ARRAY_COLOR].append(Color.WEB_GREEN)
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(0.4,0,1))
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(0.4,0,-1))
	grid_array[Mesh.ARRAY_COLOR].append(Color.WEB_GREEN)
	grid_array[Mesh.ARRAY_COLOR].append(Color.WEB_GREEN)
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(0.2,0,1))
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(0.2,0,-1))
	grid_array[Mesh.ARRAY_COLOR].append(Color.WEB_GREEN)
	grid_array[Mesh.ARRAY_COLOR].append(Color.WEB_GREEN)
	#vetical grid -4, 0.2 increment
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(-1,0,1))
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(-1,0,-1))
	grid_array[Mesh.ARRAY_COLOR].append(Color.WEB_GREEN)
	grid_array[Mesh.ARRAY_COLOR].append(Color.WEB_GREEN)
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(-0.8,0,1))
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(-0.8,0,-1))
	grid_array[Mesh.ARRAY_COLOR].append(Color.WEB_GREEN)
	grid_array[Mesh.ARRAY_COLOR].append(Color.WEB_GREEN)
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(-0.6,0,1))
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(-0.6,0,-1))
	grid_array[Mesh.ARRAY_COLOR].append(Color.WEB_GREEN)
	grid_array[Mesh.ARRAY_COLOR].append(Color.WEB_GREEN)
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(-0.4,0,1))
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(-0.4,0,-1))
	grid_array[Mesh.ARRAY_COLOR].append(Color.WEB_GREEN)
	grid_array[Mesh.ARRAY_COLOR].append(Color.WEB_GREEN)
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(-0.2,0,1))
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(-0.2,0,-1))
	grid_array[Mesh.ARRAY_COLOR].append(Color.WEB_GREEN)
	grid_array[Mesh.ARRAY_COLOR].append(Color.WEB_GREEN)
	#horizontal grid +4, 0.2 increment
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(1.0,0,1))
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(-1.0,0,1))
	grid_array[Mesh.ARRAY_COLOR].append(Color.DARK_RED)
	grid_array[Mesh.ARRAY_COLOR].append(Color.DARK_RED)
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(1.0,0,0.8))
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(-1.0,0,0.8))
	grid_array[Mesh.ARRAY_COLOR].append(Color.DARK_RED)
	grid_array[Mesh.ARRAY_COLOR].append(Color.DARK_RED)
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(1.0,0,0.6))
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(-1.0,0,0.6))
	grid_array[Mesh.ARRAY_COLOR].append(Color.DARK_RED)
	grid_array[Mesh.ARRAY_COLOR].append(Color.DARK_RED)
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(1.0,0,0.4))
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(-1.0,0,0.4))
	grid_array[Mesh.ARRAY_COLOR].append(Color.DARK_RED)
	grid_array[Mesh.ARRAY_COLOR].append(Color.DARK_RED)
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(1.0,0,0.2))
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(-1.0,0,0.2))
	grid_array[Mesh.ARRAY_COLOR].append(Color.DARK_RED)
	grid_array[Mesh.ARRAY_COLOR].append(Color.DARK_RED)
	#horizontal grid -4, 0.2 increment
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(1.0,0,-1))
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(-1.0,0,-1))
	grid_array[Mesh.ARRAY_COLOR].append(Color.DARK_RED)
	grid_array[Mesh.ARRAY_COLOR].append(Color.DARK_RED)
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(1.0,0,-0.8))
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(-1.0,0,-0.8))
	grid_array[Mesh.ARRAY_COLOR].append(Color.DARK_RED)
	grid_array[Mesh.ARRAY_COLOR].append(Color.DARK_RED)
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(1.0,0,-0.6))
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(-1.0,0,-0.6))
	grid_array[Mesh.ARRAY_COLOR].append(Color.DARK_RED)
	grid_array[Mesh.ARRAY_COLOR].append(Color.DARK_RED)
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(1.0,0,-0.4))
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(-1.0,0,-0.4))
	grid_array[Mesh.ARRAY_COLOR].append(Color.DARK_RED)
	grid_array[Mesh.ARRAY_COLOR].append(Color.DARK_RED)
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(1.0,0,-0.2))
	grid_array[Mesh.ARRAY_VERTEX].append(Vector3(-1.0,0,-0.2))
	grid_array[Mesh.ARRAY_COLOR].append(Color.DARK_RED)
	grid_array[Mesh.ARRAY_COLOR].append(Color.DARK_RED)
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_LINES, grid_array)
